### ISSUE TITLE
[Solved] Scaling issue #14 again?

### ISSUE THREAD

**Issue by thatso** [janh/go-dsl#17]
I'm experiencing scaling issues which resemble the ones solved with #14: the graphs seem to be cut off on the right border relative to the legends.

![image](https://github.com/janh/go-dsl/assets/40745263/4d321d2b-ad7f-4ae3-8d85-b583c242bc7d)

My modem is a Technicolor DGA4132 with custom firmware based on the Broadcom chipset with `xdslctl`.

**Comment by janh** [comment]
I assume what you mean is that the data in the graph already stops at around carrier 7770 / 33.5 MHz? This is not a scaling issue, it is the actual data. Some network operators (like Deutsche Telekom) don't actually make use of the entire frequency range. You can check the band values reported by `xdslctl info --pbParams` and compare them with the graph to make sure it is correct.

The previous issue #14 affected only the Hlog (channel characteristic) graph on Fritzboxes. If you look at the screenshot in that issue, the problem were the two lines around 2.5 MHz and 5 MHz which actually belong in the green (upstream) area.

**Comment by thatso** [comment]
Thank you for your fast reaction and spot-on explanation. :+1:
The relevant output of `xdslctl info --pbParams` gives:
```
Medley Phase (Final) Band Plan
US: (7,60) (871,1205) (1972,2771) 
DS: (65,859) (1216,1961) (2793,7751) 
```
As you suspected, I was focussing on what looked like a missing frequency range as I did not expect my network operator to make a hard cut at the upper end. :open_mouth:
Happily closing this as resolved. :smile:
